spring.application.name=01blog

spring.datasource.url=jdbc:postgresql://localhost:5432/blogdb
spring.datasource.username=bloguser
spring.datasource.password=blogpass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret Key (change this in production)
jwt.secret=mySecretKey123456789012345678901234567890

# CORS for Angular
app.frontend.url=http://localhost:4200
# Email Configuration

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=itisaboutit01@gmail.com
spring.mail.password=dtev utvh ybra npul
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000

# Cloudinary Configuration
cloudinary.cloud-name=dk5ivb1vm
cloudinary.api-key=258424529676278
cloudinary.api-secret=gAQtcHTTSBkhsVijT9sH7aUCNvA

# spring.servlet.multipart.max-file-size=100MB    # For videos
# spring.servlet.multipart.max-request-size=100MB

# Allowed file types (client-side validation only, Cloudinary handles server-side)
# Images: jpg, jpeg, png, gif, webp
# Videos: mp4, avi, mov, wmv, flv
# Files: pdf, doc, docx, txt
# File upload limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true

# Server
server.port=8080

# Logging
logging.level.com._Talent._blog=DEBUG
logging.level.com.cloudinary=DEBUG
logging.level.org.springframework.web=DEBUG